"""The Wiener-Hammerstein SSM candidate.

These check that the candidate is *scoreable* -- under budget, affine in length, and
the same function in both of its forms. Whether it is any *good* is an ESR question,
and no test can answer it; that takes a trained run against the panel.
"""

import pytest
import torch

from harness.constants import ELEMENTWISE_BUDGET_FACTOR
from harness.cost import count_cost
from harness.reference import (
    A2_RECEPTIVE_FIELD,
    A2_STANDARD_MACS,
    a2_standard,
)
from harness.streaming import MAX_EQUIVALENCE_ESR
from train import WH_R_MAX, ResonantBank, WienerHammersteinSSM


@pytest.fixture(scope="module")
def model():
    torch.manual_seed(0)
    return WienerHammersteinSSM()


@pytest.fixture(scope="module")
def report(model):
    return count_cost(model, verify_at=8192)


def test_fits_inside_the_a2_compute_cap(report):
    assert report.used_streaming_form
    assert report.macs_per_sample < A2_STANDARD_MACS
    assert report.is_linear


def test_does_not_dodge_the_cap_through_elementwise_work(report):
    """A cheap-MAC architecture that moved its work into pointwise ops would be
    cheating; the elementwise budget is the check, so assert against it explicitly."""
    a2 = count_cost(a2_standard(), input_samples=32768)
    assert report.elementwise_per_sample <= a2.elementwise_per_sample * ELEMENTWISE_BUDGET_FACTOR


def test_the_two_forms_are_the_same_function(report):
    assert report.equivalence_esr < MAX_EQUIVALENCE_ESR


@pytest.mark.parametrize("length", [1, 2, 3, 1023, 1024, 1025, 3000])
def test_the_scan_matches_the_recurrence_at_awkward_lengths(model, length):
    """The doubling scan covers 2^k terms after k rounds, so lengths just above and
    below a power of two are where an off-by-one in the round count would show. T=1
    and T=2 also check the loop degenerates correctly rather than indexing an empty
    slice."""
    torch.manual_seed(length)
    x = (torch.rand(1, length) * 2 - 1) * 0.5
    with torch.no_grad():
        scanned = model._run(x, streaming=False)
        recurrent = model._run(x, streaming=True)
    err = torch.mean((scanned.double() - recurrent.double()) ** 2)
    scale = torch.mean(recurrent.double() ** 2) + 1e-30
    assert float(err / scale) < MAX_EQUIVALENCE_ESR


@pytest.mark.parametrize("logit", [60.0, 20.0, 17.0, 0.0, -60.0])
def test_poles_stay_inside_the_unit_circle_for_any_parameter_value(logit):
    """Stability is structural here, not a training-time hope.

    Note what this is really guarding. Plain ``sigmoid`` is *not* enough: in float32
    it returns exactly 1.0 from a logit of about 17 upward, which places a pole on
    the unit circle -- a pure integrator, and a zero drive gain whose derivative is
    infinite. The WH_R_MAX factor is what makes the claim true.
    """
    bank = ResonantBank(1, 1, 8)
    with torch.no_grad():
        bank.r_logit.fill_(logit)
    r = bank._radius().detach()
    assert float(r.max()) < 1.0
    assert float(r.min()) > 0.0
    assert float(r.max()) <= WH_R_MAX


def test_the_extreme_pole_still_yields_finite_gradients():
    """The failure mode WH_R_MAX prevents is silent: NaN gradients on step one."""
    bank = ResonantBank(1, 1, 8)
    with torch.no_grad():
        bank.r_logit.fill_(60.0)
    x = torch.randn(1, 1, 512) * 0.1
    bank(x, streaming=False).pow(2).mean().backward()
    assert torch.isfinite(bank.r_logit.grad).all()
    assert torch.isfinite(bank.b_proj.grad).all()


def test_a_bank_can_actually_fit_a_second_order_target():
    """Gradients existing is not the same as the parameterization being learnable.

    The target is one damped resonance, which a single block represents exactly, so
    this is a floor: if a bank cannot close most of the gap on a target inside its own
    hypothesis class, the ``sigmoid``/``sqrt(1-r^2)`` reparameterization is the
    problem and no ESR from the full cascade would mean anything.
    """
    torch.manual_seed(0)
    n = 2048
    x = torch.randn(1, 1, n) * 0.3

    # Target: a single resonance at r = 0.995, theta = 0.05 rad/sample. Generated by
    # a bank rather than a Python loop -- same arithmetic, three orders faster.
    target = ResonantBank(1, 1, 1)
    with torch.no_grad():
        target.r_logit.fill_(float(torch.logit(torch.tensor(0.995 / WH_R_MAX))))
        target.theta.fill_(0.05)
        target.b_proj.fill_(1.0)
        target.c_proj.weight.copy_(torch.tensor([[1.0, 0.0]]))
        target.c_proj.bias.zero_()
        y = target(x, streaming=False)
    y = y / y.std()

    bank = ResonantBank(1, 1, 8)
    opt = torch.optim.Adam(bank.parameters(), lr=0.02)
    first = last = None
    for step in range(150):
        pred = bank(x, streaming=False)
        loss = torch.mean((pred - y) ** 2) / torch.mean(y**2)
        opt.zero_grad(set_to_none=True)
        loss.backward()
        opt.step()
        if step == 0:
            first = float(loss.detach())
        last = float(loss.detach())

    assert last == last, "loss went NaN"
    assert last < 0.5 * first, f"bank did not learn: {first:.4f} -> {last:.4f}"


def test_receptive_field_matches_a2_so_the_scored_region_is_identical(model):
    assert model.receptive_field == A2_RECEPTIVE_FIELD


def test_gradients_reach_the_pole_parameters(model):
    """A recurrence whose decay and frequency do not train is just a random filter
    bank with a learned mixer -- the architecture's whole claim would be void."""
    torch.manual_seed(3)
    x = (torch.rand(1, 1024) * 2 - 1) * 0.5
    model.zero_grad(set_to_none=True)
    model._run(x, streaming=False).pow(2).mean().backward()
    for name, bank in (("1", model.stage1), ("2", model.stage2), ("3", model.stage3)):
        assert bank.r_logit.grad is not None and bank.r_logit.grad.abs().sum() > 0, name
        assert bank.theta.grad is not None and bank.theta.grad.abs().sum() > 0, name
    model.zero_grad(set_to_none=True)
